
abstract=This content pattern (E&O)  models the observation of experience as resulting from a direct engagement in an activity and reflected in an observation prompted from the person engaged in the activity. 
E&O represents an experience through its factual, cognitive, phenomenological and critical coordinates, which all lend themselves to further specialisation in the ontologies where the CP will be instantiated.
ontologyTitle=Experience & Observation (E&O) Pattern
ontologyPrefix=[Ontology NS Prefix]
ontologyNamespaceURI=http://modellingdh.github.io/ont/odp/experience
ontologyName=Experience & Observation (E&O) Pattern
thisVersionURI=https://raw.githubusercontent.com/modellingDH/odp_experience/master/owl/cp_experience.owl.ttl
latestVersionURI=
previousVersionURI=
dateOfRelease=
ontologyRevisionNumber=
licenseURI=null
licenseName=null
licenseIconURL=null
citeAs=https://orcid.org/0000-0002-3639-3622,https://orcid.org/0000-0002-9272-908X,https://orcid.org/0000-0003-3807-5019. Experience & Observation (E&O) Pattern. Retrieved from: https://raw.githubusercontent.com/modellingDH/odp_experience/master/owl/cp_experience.owl.ttl
DOI=
status=Ontology Specification Draft
backwardsCompatibleWith=
publisher=null
publisherURI=null
publisherInstitution=null
publisherInstitutionURI=null
authors=https://orcid.org/0000-0002-3639-3622;https://orcid.org/0000-0002-9272-908X;https://orcid.org/0000-0003-3807-5019
authorsURI=https://orcid.org/0000-0002-3639-3622;https://orcid.org/0000-0002-9272-908X;https://orcid.org/0000-0003-3807-5019
authorsInstitution=;;
authorsInstitutionURI=;;
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=cpannotationschema.owl
importedOntologyURIs=http://www.ontologydesignpatterns.org/schemas/cpannotationschema.owl
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.xml
TurtleSerialization=ontology.ttl
N3Serialization=ontology.nt
JSONLDSerialization=ontology.json
